### ISSUE TITLE
代码很多问题

### ISSUE THREAD

**Issue by Henryflee** [chin-gyou/dialogue-utterance-rewriter#9]
基于LSTM其实也也无所谓的
（1）数据没有负样本；
（2）代码问题太多，跑不通；
（3）即使改的能跑通后，发现数据格式和代码中写的对不上。

**Comment by chin-gyou** [comment]
抱歉之前上传的代码整理有误，已更新。PS. 数据为最新的标注数据，数据质量比ACL投稿时期好了很多。
